Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2022
Var
   numero,resultado,i:inteiro


Inicio
   leia(numero)

       resultado <- 1

   para i de 1 ate numero faca

       resultado <- resultado * i

   fimpara

   escreval(resultado)


Fimalgoritmo